### PR TITLE
Web dashboard inside Docker image

### PR DESCRIPTION
**Pull request by GianlucaBortoli**
Added the Web interface/dashboard to the docker image (and little refactor for comments in the `Makefile`).

**NOTE**: I temporary excluded ElasticSearch from `DEFAULT_APIS` list inside `localstack/mock/infra.py` due to #46

### CODE REVIEW

**Comment by GianlucaBortoli** [comment]
I think the test coverage decreased due to the _temporary_ exclusion of ES

**Comment by whummer** [comment]
Thanks for the PR. I'm adding some comments inline in the code. Also, can you please raise the PR against the main repository on Bitbucket (https://bitbucket.org/atlassian/localstack)?

We will also require a signed Contributors License Agreement (see README). The signing process is very fast, literally takes only 1-2 minutes. Thanks

**Comment by GianlucaBortoli** [comment]
Bitbucket is giving me `Access denied` if I try to create a new pull request against the main repo.
Is there something I'm missing?

**Comment by whummer** [comment]
Maybe PRs are disabled for your repo? You need to create the PR in the target repo, i.e., can you try raising it from here: https://bitbucket.org/atlassian/localstack/pull-requests/new Thanks

**Comment by whummer** [comment]
If I try to access this page, I also get an "Access denied" error, but my guess would be that this is because I don't have permissions to create PRs on that repo? https://bitbucket.org/GianlucaBortoli/localstack/pull-requests/new

**Comment by GianlucaBortoli** [comment]
I found out that PR are possible only if you forked the original repo.
I finally managed to successfully issue the PR on Bitbucket.

**Comment by whummer** [comment]
Moved this PR to the Bitbucket repo: https://bitbucket.org/atlassian/localstack/pull-requests/31

**Pull request closed without merging**
